### ISSUE TITLE
希望可以支持8.9.80版本

### ISSUE THREAD

**Issue by airdm** [BennettChina/docker-qsign#1]
8.9.80 的txlib  [https://github.com/rhwong/unidbg-fetch-qsign-onekey/tree/1.1.9-fix2/txlib/8.9.80](url)

**Comment by BennettChina** [comment]
放在txlib里吗？没改默认的 `8.9.63` 也是 `go-cqhttp` 默认用的这个。如果是像其他几个版本一样，放在一个文件夹里也可以。
